name: practice-workflow
on: [push,pull_request]

jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: python version
        run: |
          python --version
          pip --version
